development:
  # required. default should be fine if your postgresql server is running locally.
  DATABASE_URL: postgres://localhost

  # required for login to work. register an application @ twitch.tv/settings/connections.
  # when registering, use a redirect uri of http://localhost:3000/auth/twitch/callback
  TWITCH_CLIENT_ID:
  TWITCH_CLIENT_SECRET:

test:
  # required to be able to run tests
  DATABASE_URL: postgres://localhost

# you don't need to fill out anything past here unless you're deploying this somewhere
production:
  DATABASE_URL:

  TWITCH_CLIENT_ID:
  TWITCH_CLIENT_SECRET:

  NEW_RELIC_LICENSE_KEY:
  ROLLBAR_ACCESS_TOKEN:

  # used for signing cookies. generate a secure one with `rake secret`
  SECRET_KEY_BASE:
